import 'dotenv/config';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient, ProductCategory, ProductStatus } from '@prisma/client';

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) throw new Error('DATABASE_URL is required to seed products');

const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString: databaseUrl }),
});
const MOBILE = ProductCategory.MOBILE;
const LAPTOP = ProductCategory.LAPTOP;
const TABLET = ProductCategory.TABLET;
const AUDIO = ProductCategory.AUDIO;
const WATCH = ProductCategory.WATCH;
const ACCESSORY = ProductCategory.ACCESSORY;
const ACTIVE = ProductStatus.ACTIVE;

const products = [
  {
    title: 'Samsung Galaxy S25 Ultra',
    sku: 'MOB-SAM-S25U-256',
    slug: 'samsung-galaxy-s25-ultra',
    brand: 'Samsung',
    category: MOBILE,
    shortDescription: 'Flagship Android smartphone with AI features.',
    description:
      'Samsung Galaxy S25 Ultra featuring Snapdragon chipset, 256GB storage, 12GB RAM, 200MP camera and 6.9-inch Dynamic AMOLED display.',
    price: 159999,
    compareAtPrice: 169999,
    quantity: 20,
    status: ACTIVE,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    specifications: {
      Display: '6.9-inch Dynamic AMOLED 2X',
      Processor: 'Snapdragon 8 Elite',
      RAM: '12 GB',
      Storage: '256 GB',
      Battery: '5000 mAh',
      Camera: '200 MP',
    },
  },
  {
    title: 'Apple iPhone 17 Pro',
    sku: 'MOB-APL-IP17P-256',
    slug: 'apple-iphone-17-pro',
    brand: 'Apple',
    category: MOBILE,
    shortDescription: 'Premium iPhone with Pro camera system.',
    description:
      'Apple iPhone 17 Pro with A19 Pro chip, 256GB storage and advanced camera capabilities.',
    price: 199999,
    compareAtPrice: 214999,
    quantity: 15,
    status: ACTIVE,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    specifications: {
      Display: '6.3-inch Super Retina XDR',
      Processor: 'A19 Pro',
      RAM: '12 GB',
      Storage: '256 GB',
      Battery: '4200 mAh',
      Camera: '48 MP Triple Camera',
    },
  },
  {
    title: 'Google Pixel 10 Pro',
    sku: 'MOB-GGL-PX10P-256',
    slug: 'google-pixel-10-pro',
    brand: 'Google',
    category: MOBILE,
    shortDescription: 'AI-powered Pixel flagship smartphone.',
    description:
      'Google Pixel 10 Pro with Tensor G5 processor, 256GB storage and exceptional camera performance.',
    price: 149999,
    compareAtPrice: 159999,
    quantity: 18,
    status: ACTIVE,
    isFeatured: true,
    isTrending: true,
    isBestSeller: false,
    specifications: {
      Display: '6.8-inch OLED',
      Processor: 'Google Tensor G5',
      RAM: '12 GB',
      Storage: '256 GB',
      Battery: '5100 mAh',
      Camera: '50 MP Triple Camera',
    },
  },
  {
    title: 'OnePlus 14',
    sku: 'MOB-ONE-14-256',
    slug: 'oneplus-14',
    brand: 'OnePlus',
    category: MOBILE,
    shortDescription: 'Fast and smooth flagship experience.',
    description:
      'OnePlus 14 with Snapdragon processor, AMOLED display and 100W fast charging.',
    price: 99999,
    compareAtPrice: 109999,
    quantity: 30,
    status: ACTIVE,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    specifications: {
      Display: '6.82-inch AMOLED',
      Processor: 'Snapdragon 8 Elite',
      RAM: '12 GB',
      Storage: '256 GB',
      Battery: '5500 mAh',
      Charging: '100W',
    },
  },
  {
    title: 'Xiaomi 16 Pro',
    sku: 'MOB-XIA-16P-512',
    slug: 'xiaomi-16-pro',
    brand: 'Xiaomi',
    category: MOBILE,
    shortDescription: 'High-end smartphone with Leica camera.',
    description:
      'Xiaomi 16 Pro featuring Leica optics, Snapdragon processor and 512GB storage.',
    price: 114999,
    compareAtPrice: 124999,
    quantity: 25,
    status: ACTIVE,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    specifications: {
      Display: '6.73-inch AMOLED',
      Processor: 'Snapdragon 8 Elite',
      RAM: '16 GB',
      Storage: '512 GB',
      Battery: '5400 mAh',
      Camera: '50 MP Leica',
    },
  },
  {
    title: 'Nothing Phone 4',
    sku: 'MOB-NTG-PH4-256',
    slug: 'nothing-phone-4',
    brand: 'Nothing',
    category: MOBILE,
    shortDescription: 'Unique transparent design with Glyph interface.',
    description:
      'Nothing Phone 4 delivers clean Android experience and signature Glyph lighting.',
    price: 79999,
    compareAtPrice: 85999,
    quantity: 40,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Display: '6.7-inch OLED',
      Processor: 'Snapdragon 8s Gen 4',
      RAM: '12 GB',
      Storage: '256 GB',
      Battery: '5000 mAh',
    },
  },
  {
    title: 'Realme GT 8 Pro',
    sku: 'MOB-RLM-GT8P-256',
    slug: 'realme-gt-8-pro',
    brand: 'Realme',
    category: MOBILE,
    shortDescription: 'Performance-focused gaming smartphone.',
    description:
      'Realme GT 8 Pro with flagship chipset and ultra-fast charging.',
    price: 69999,
    compareAtPrice: 74999,
    quantity: 35,
    status: ACTIVE,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    specifications: {
      Display: '6.78-inch AMOLED',
      Processor: 'Snapdragon 8 Gen 4',
      RAM: '12 GB',
      Storage: '256 GB',
      Battery: '6000 mAh',
    },
  },
  {
    title: 'Vivo X300 Pro',
    sku: 'MOB-VIV-X300P-512',
    slug: 'vivo-x300-pro',
    brand: 'Vivo',
    category: MOBILE,
    shortDescription: 'Professional photography smartphone.',
    description:
      'Vivo X300 Pro featuring ZEISS optics, flagship chipset and premium display.',
    price: 119999,
    compareAtPrice: 129999,
    quantity: 22,
    status: ACTIVE,
    isFeatured: true,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Display: '6.8-inch AMOLED',
      Processor: 'Dimensity 9500',
      RAM: '16 GB',
      Storage: '512 GB',
      Camera: 'ZEISS Triple Camera',
    },
  },
  {
    title: 'Oppo Find X9 Pro',
    sku: 'MOB-OPP-FX9P-512',
    slug: 'oppo-find-x9-pro',
    brand: 'Oppo',
    category: MOBILE,
    shortDescription: 'Premium flagship with Hasselblad camera.',
    description:
      'Oppo Find X9 Pro featuring flagship performance and advanced photography.',
    price: 129999,
    compareAtPrice: 139999,
    quantity: 17,
    status: ACTIVE,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    specifications: {
      Display: '6.82-inch AMOLED',
      Processor: 'Snapdragon 8 Elite',
      RAM: '16 GB',
      Storage: '512 GB',
      Battery: '5600 mAh',
    },
  },
  {
    title: 'Motorola Edge 70 Ultra',
    sku: 'MOB-MOT-E70U-256',
    slug: 'motorola-edge-70-ultra',
    brand: 'Motorola',
    category: MOBILE,
    shortDescription: 'Premium Android smartphone with clean UI.',
    description:
      'Motorola Edge 70 Ultra featuring Snapdragon chipset, OLED display and premium design.',
    price: 89999,
    compareAtPrice: 96999,
    quantity: 28,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    specifications: {
      Display: '6.7-inch OLED',
      Processor: 'Snapdragon 8 Gen 4',
      RAM: '12 GB',
      Storage: '256 GB',
      Battery: '5000 mAh',
    },
  },

  // ---- LAPTOP ----
  {
    title: 'Apple MacBook Pro 16',
    sku: 'LAP-APL-MBP16-512',
    slug: 'apple-macbook-pro-16',
    brand: 'Apple',
    category: LAPTOP,
    shortDescription: 'Pro performance in a premium aluminium chassis.',
    description:
      'Apple MacBook Pro 16 with M4 Max chip, Liquid Retina XDR display and all-day battery for demanding creative work.',
    price: 329000,
    compareAtPrice: 349000,
    quantity: 10,
    status: ACTIVE,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    specifications: {
      Display: '16.2-inch Liquid Retina XDR',
      Chip: 'M4 Max',
      RAM: '48 GB',
      Storage: '512 GB',
      Battery: '22 hours',
    },
  },
  {
    title: 'Dell XPS 16',
    sku: 'LAP-DLL-XPS16-1TB',
    slug: 'dell-xps-16',
    brand: 'Dell',
    category: LAPTOP,
    shortDescription: 'Slim flagship Windows ultrabook with OLED panel.',
    description:
      'Dell XPS 16 with Intel Core Ultra 9, OLED display and premium CNC-machined design.',
    price: 289000,
    compareAtPrice: 309000,
    quantity: 8,
    status: ACTIVE,
    isFeatured: true,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Display: '16.3-inch OLED',
      Processor: 'Core Ultra 9',
      RAM: '32 GB',
      Storage: '1 TB',
      Weight: '1.9 kg',
    },
  },
  {
    title: 'Lenovo ThinkPad X1 Carbon',
    sku: 'LAP-LNV-TPX1C-1TB',
    slug: 'lenovo-thinkpad-x1-carbon',
    brand: 'Lenovo',
    category: LAPTOP,
    shortDescription: 'Featherweight business laptop built to last.',
    description:
      'Lenovo ThinkPad X1 Carbon Gen 13 with Core Ultra 7, carbon-fibre body and legendary keyboard.',
    price: 235000,
    compareAtPrice: null,
    quantity: 12,
    status: ACTIVE,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    specifications: {
      Display: '14-inch WUXGA',
      Processor: 'Core Ultra 7',
      RAM: '32 GB',
      Storage: '1 TB',
      Weight: '1.09 kg',
    },
  },
  {
    title: 'ASUS ROG Zephyrus G16',
    sku: 'LAP-ASU-ROGG16-1TB',
    slug: 'asus-rog-zephyrus-g16',
    brand: 'ASUS',
    category: LAPTOP,
    shortDescription: 'Portable gaming laptop with RTX graphics.',
    description:
      'ASUS ROG Zephyrus G16 with Ryzen AI 9, RTX 5070 GPU and 240Hz OLED display for gaming on the move.',
    price: 269000,
    compareAtPrice: 285000,
    quantity: 9,
    status: ACTIVE,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    specifications: {
      Display: '16-inch OLED 240Hz',
      Processor: 'Ryzen AI 9 HX 370',
      GPU: 'RTX 5070',
      RAM: '32 GB',
      Storage: '1 TB',
    },
  },
  {
    title: 'HP Spectre x360 14',
    sku: 'LAP-HP-SPX14-1TB',
    slug: 'hp-spectre-x360-14',
    brand: 'HP',
    category: LAPTOP,
    shortDescription: 'Convertible 2-in-1 with a vibrant OLED screen.',
    description:
      'HP Spectre x360 14 with Core Ultra 7, 2.8K OLED touch display and long battery life.',
    price: 215000,
    compareAtPrice: 229000,
    quantity: 11,
    status: ACTIVE,
    isFeatured: true,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Display: '14-inch 2.8K OLED',
      Processor: 'Core Ultra 7',
      RAM: '32 GB',
      Storage: '1 TB',
      Battery: '16 hours',
    },
  },
  {
    title: 'Acer Swift Go 14',
    sku: 'LAP-ACR-SWG14-512',
    slug: 'acer-swift-go-14',
    brand: 'Acer',
    category: LAPTOP,
    shortDescription: 'Affordable everyday ultrabook with OLED clarity.',
    description:
      'Acer Swift Go 14 with Core Ultra 5, 2.8K OLED display and a light all-metal body.',
    price: 125000,
    compareAtPrice: null,
    quantity: 15,
    status: ACTIVE,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    specifications: {
      Display: '14-inch 2.8K OLED',
      Processor: 'Core Ultra 5',
      RAM: '16 GB',
      Storage: '512 GB',
    },
  },
  {
    title: 'Microsoft Surface Laptop 6',
    sku: 'LAP-MSR-SL6-512',
    slug: 'microsoft-surface-laptop-6',
    brand: 'Microsoft',
    category: LAPTOP,
    shortDescription: 'Elegant laptop with Snapdragon efficiency.',
    description:
      'Microsoft Surface Laptop 6 with Snapdragon X Elite, PixelSense display and exceptional battery life.',
    price: 219000,
    compareAtPrice: 234000,
    quantity: 7,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    specifications: {
      Display: '13.8-inch PixelSense',
      Processor: 'Snapdragon X Elite',
      RAM: '16 GB',
      Storage: '512 GB',
      Battery: '20 hours',
    },
  },
  {
    title: 'Razer Blade 16',
    sku: 'LAP-RZR-BL16-1TB',
    slug: 'razer-blade-16',
    brand: 'Razer',
    category: LAPTOP,
    shortDescription: 'Thin-and-light powerhouse for creators and gamers.',
    description:
      'Razer Blade 16 with RTX 5090 GPU, QHD+ 240Hz display and CNC aluminium unibody.',
    price: 359000,
    compareAtPrice: 379000,
    quantity: 5,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Display: '16-inch QHD+ 240Hz',
      GPU: 'RTX 5090',
      RAM: '32 GB',
      Storage: '1 TB',
      Weight: '2.4 kg',
    },
  },
  {
    title: 'LG Gram Pro 17',
    sku: 'LAP-LG-GP17-1TB',
    slug: 'lg-gram-pro-17',
    brand: 'LG',
    category: LAPTOP,
    shortDescription: 'Ultra-light 17-inch laptop with a huge screen.',
    description:
      'LG Gram Pro 17 weighing just 1.29 kg with Core Ultra 7, WQXGA display and a massive battery.',
    price: 249000,
    compareAtPrice: 265000,
    quantity: 6,
    status: ACTIVE,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    specifications: {
      Display: '17-inch WQXGA',
      Processor: 'Core Ultra 7',
      RAM: '32 GB',
      Storage: '1 TB',
      Weight: '1.29 kg',
    },
  },
  {
    title: 'Framework Laptop 16',
    sku: 'LAP-FWK-FW16-1TB',
    slug: 'framework-laptop-16',
    brand: 'Framework',
    category: LAPTOP,
    shortDescription: 'Modular, repairable 16-inch laptop with discrete GPU.',
    description:
      'Framework Laptop 16 with Ryzen 7 7840HS, Radeon RX 7700S graphics and user-upgradable modules.',
    price: 275000,
    compareAtPrice: null,
    quantity: 4,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Display: '16-inch QHD+',
      Processor: 'Ryzen 7 7840HS',
      Graphics: 'RX 7700S',
      RAM: '32 GB',
      Storage: '1 TB',
    },
  },

  // ---- TABLET ----
  {
    title: 'Apple iPad Pro 13',
    sku: 'TAB-APL-IPDP13-256',
    slug: 'apple-ipad-pro-13',
    brand: 'Apple',
    category: TABLET,
    shortDescription: 'M4-powered tablet with an Ultra Retina XDR screen.',
    description:
      'Apple iPad Pro 13 with M4 chip, Ultra Retina XDR display and slim design for pro workloads.',
    price: 164000,
    compareAtPrice: 179000,
    quantity: 12,
    status: ACTIVE,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    specifications: {
      Display: '13-inch Ultra Retina XDR',
      Chip: 'M4',
      Storage: '256 GB',
      Weight: '579 g',
    },
  },
  {
    title: 'Apple iPad Air 11',
    sku: 'TAB-APL-IPDA11-128',
    slug: 'apple-ipad-air-11',
    brand: 'Apple',
    category: TABLET,
    shortDescription: 'Versatile M3 tablet for work and play.',
    description:
      'Apple iPad Air 11 with M3 chip, Liquid Retina display and Apple Pencil Pro support.',
    price: 109000,
    compareAtPrice: 119000,
    quantity: 14,
    status: ACTIVE,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    specifications: {
      Display: '11-inch Liquid Retina',
      Chip: 'M3',
      Storage: '128 GB',
    },
  },
  {
    title: 'Samsung Galaxy Tab S10 Ultra',
    sku: 'TAB-SAM-TS10U-256',
    slug: 'samsung-galaxy-tab-s10-ultra',
    brand: 'Samsung',
    category: TABLET,
    shortDescription: 'Giant 14.6-inch AMOLED canvas with S Pen.',
    description:
      'Samsung Galaxy Tab S10 Ultra with 14.6-inch Dynamic AMOLED display and bundled S Pen.',
    price: 149000,
    compareAtPrice: 159000,
    quantity: 10,
    status: ACTIVE,
    isFeatured: true,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Display: '14.6-inch Dynamic AMOLED',
      Processor: 'Dimensity 9300+',
      Storage: '256 GB',
      S_Pen: 'Included',
    },
  },
  {
    title: 'Samsung Galaxy Tab S10+',
    sku: 'TAB-SAM-TS10P-256',
    slug: 'samsung-galaxy-tab-s10-plus',
    brand: 'Samsung',
    category: TABLET,
    shortDescription: 'Large-screen Android tablet for media and notes.',
    description:
      'Samsung Galaxy Tab S10+ with 12.4-inch AMOLED display and 12GB RAM.',
    price: 119000,
    compareAtPrice: 129000,
    quantity: 13,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    specifications: {
      Display: '12.4-inch AMOLED',
      RAM: '12 GB',
      Storage: '256 GB',
    },
  },
  {
    title: 'Xiaomi Pad 7 Pro',
    sku: 'TAB-XIA-P7P-256',
    slug: 'xiaomi-pad-7-pro',
    brand: 'Xiaomi',
    category: TABLET,
    shortDescription: 'Fast 144Hz tablet at a friendly price.',
    description:
      'Xiaomi Pad 7 Pro with Snapdragon 8s Gen 3, 144Hz display and 256GB storage.',
    price: 64900,
    compareAtPrice: 69900,
    quantity: 18,
    status: ACTIVE,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    specifications: {
      Display: '11.2-inch 144Hz',
      Processor: 'Snapdragon 8s Gen 3',
      Storage: '256 GB',
    },
  },
  {
    title: 'OnePlus Pad 2',
    sku: 'TAB-ONE-OP2-256',
    slug: 'oneplus-pad-2',
    brand: 'OnePlus',
    category: TABLET,
    shortDescription: 'Smooth 144Hz tablet with flagship chipset.',
    description:
      'OnePlus Pad 2 with Snapdragon 8 Gen 3 and a large 12.1-inch 144Hz display.',
    price: 72900,
    compareAtPrice: 78900,
    quantity: 16,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    specifications: {
      Display: '12.1-inch 144Hz LCD',
      Processor: 'Snapdragon 8 Gen 3',
      Storage: '256 GB',
    },
  },
  {
    title: 'Lenovo Tab Extreme',
    sku: 'TAB-LNV-TBE-256',
    slug: 'lenovo-tab-extreme',
    brand: 'Lenovo',
    category: TABLET,
    shortDescription: 'Premium 14.5-inch OLED productivity tablet.',
    description:
      'Lenovo Tab Extreme with 14.5-inch 3K OLED display and Dimensity 9000 chipset.',
    price: 99000,
    compareAtPrice: 109000,
    quantity: 8,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Display: '14.5-inch 3K OLED',
      Processor: 'Dimensity 9000',
      Storage: '256 GB',
    },
  },
  {
    title: 'Google Pixel Tablet 2',
    sku: 'TAB-GGL-PXT2-256',
    slug: 'google-pixel-tablet-2',
    brand: 'Google',
    category: TABLET,
    shortDescription: 'Tensor-powered home tablet with dock.',
    description:
      'Google Pixel Tablet 2 with Tensor G4 and a speaker dock for home and media use.',
    price: 109000,
    compareAtPrice: 119000,
    quantity: 9,
    status: ACTIVE,
    isFeatured: true,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Display: '11-inch LCD',
      Processor: 'Tensor G4',
      Storage: '256 GB',
    },
  },
  {
    title: 'Huawei MatePad Pro 13.2',
    sku: 'TAB-HUA-MPP132-1TB',
    slug: 'huawei-matepad-pro-13-2',
    brand: 'Huawei',
    category: TABLET,
    shortDescription: 'Ultra-thin 13.2-inch OLED tablet for creatives.',
    description:
      'Huawei MatePad Pro 13.2 with 2.8K OLED display and 1TB storage in a featherweight frame.',
    price: 129000,
    compareAtPrice: 139000,
    quantity: 7,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Display: '13.2-inch 2.8K OLED',
      RAM: '16 GB',
      Storage: '1 TB',
    },
  },
  {
    title: 'Amazon Fire Max 11',
    sku: 'TAB-AMZ-FM11-128',
    slug: 'amazon-fire-max-11',
    brand: 'Amazon',
    category: TABLET,
    shortDescription: 'Budget-friendly entertainment tablet.',
    description:
      'Amazon Fire Max 11 with a 2K display for streaming, reading and light productivity.',
    price: 32900,
    compareAtPrice: 35900,
    quantity: 22,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Display: '11-inch 2K',
      RAM: '4 GB',
      Storage: '128 GB',
    },
  },

  // ---- AUDIO ----
  {
    title: 'Sony WH-1000XM6',
    sku: 'AUD-SNY-WHXM6',
    slug: 'sony-wh-1000xm6',
    brand: 'Sony',
    category: AUDIO,
    shortDescription: 'Industry-leading over-ear noise cancellation.',
    description:
      'Sony WH-1000XM6 over-ear headphones with adaptive ANC, 40-hour battery and crystal-clear calls.',
    price: 55900,
    compareAtPrice: 59900,
    quantity: 20,
    status: ACTIVE,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    specifications: {
      Type: 'Over-ear',
      ANC: 'Adaptive',
      Battery: '40 hours',
      Bluetooth: '5.3',
    },
  },
  {
    title: 'Apple AirPods Pro 3',
    sku: 'AUD-APL-APP3',
    slug: 'apple-airpods-pro-3',
    brand: 'Apple',
    category: AUDIO,
    shortDescription: 'H3-powered in-ear earbuds with spatial audio.',
    description:
      'Apple AirPods Pro 3 with the H3 chip, adaptive ANC and a refined in-ear fit.',
    price: 38900,
    compareAtPrice: 41900,
    quantity: 25,
    status: ACTIVE,
    isFeatured: true,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Type: 'In-ear',
      Chip: 'H3',
      ANC: 'Yes',
      Battery: '8 hours',
    },
  },
  {
    title: 'Samsung Galaxy Buds3 Pro',
    sku: 'AUD-SAM-GB3P',
    slug: 'samsung-galaxy-buds3-pro',
    brand: 'Samsung',
    category: AUDIO,
    shortDescription: 'Blade-styled earbuds with immersive ANC.',
    description:
      'Samsung Galaxy Buds3 Pro with blade design, two-way speakers and smart ANC.',
    price: 25900,
    compareAtPrice: 28900,
    quantity: 30,
    status: ACTIVE,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    specifications: {
      Type: 'In-ear',
      ANC: 'Yes',
      Battery: '7 hours',
      Design: 'Blade',
    },
  },
  {
    title: 'Sennheiser Momentum 4',
    sku: 'AUD-SNH-MOM4',
    slug: 'sennheiser-momentum-4',
    brand: 'Sennheiser',
    category: AUDIO,
    shortDescription: 'Studio-grade sound with 60-hour battery.',
    description:
      'Sennheiser Momentum 4 wireless headphones with exceptional audio and all-day comfort.',
    price: 45900,
    compareAtPrice: 49900,
    quantity: 12,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    specifications: {
      Type: 'Over-ear',
      ANC: 'Yes',
      Battery: '60 hours',
    },
  },
  {
    title: 'JBL Tune 770NC',
    sku: 'AUD-JBL-T770NC',
    slug: 'jbl-tune-770nc',
    brand: 'JBL',
    category: AUDIO,
    shortDescription: 'Affordable over-ear ANC with huge battery life.',
    description:
      'JBL Tune 770NC with adaptive noise cancelling and up to 70 hours of playback.',
    price: 15900,
    compareAtPrice: 17900,
    quantity: 40,
    status: ACTIVE,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    specifications: {
      Type: 'Over-ear',
      ANC: 'Yes',
      Battery: '70 hours',
    },
  },
  {
    title: 'Bose QuietComfort Ultra',
    sku: 'AUD-BOS-QCU',
    slug: 'bose-quietcomfort-ultra',
    brand: 'Bose',
    category: AUDIO,
    shortDescription: 'World-class ANC with immersive audio modes.',
    description:
      'Bose QuietComfort Ultra headphones with the most powerful noise cancellation Bose has built.',
    price: 48900,
    compareAtPrice: 52900,
    quantity: 15,
    status: ACTIVE,
    isFeatured: true,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Type: 'Over-ear',
      ANC: 'World-class',
      Battery: '24 hours',
    },
  },
  {
    title: 'Jabra Elite 10 Gen 2',
    sku: 'AUD-JBR-E10G2',
    slug: 'jabra-elite-10-gen-2',
    brand: 'Jabra',
    category: AUDIO,
    shortDescription: 'Comfortable earbuds with Dolby spatial sound.',
    description:
      'Jabra Elite 10 Gen 2 earbuds with Dolby Audio, adaptive ANC and all-day comfort.',
    price: 29900,
    compareAtPrice: 32900,
    quantity: 18,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Type: 'In-ear',
      ANC: 'Yes',
      Battery: '8 + 27 hours',
    },
  },
  {
    title: 'Anker Soundcore Space One',
    sku: 'AUD-ANK-SSO',
    slug: 'anker-soundcore-space-one',
    brand: 'Anker',
    category: AUDIO,
    shortDescription: 'Budget ANC headphones that punch above their price.',
    description:
      'Anker Soundcore Space One over-ear headphones with adaptive ANC and 40-hour playtime.',
    price: 17900,
    compareAtPrice: 19900,
    quantity: 35,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    specifications: {
      Type: 'Over-ear',
      ANC: 'Yes',
      Battery: '40 hours',
    },
  },
  {
    title: 'Sony WF-1000XM6',
    sku: 'AUD-SNY-WFXM6',
    slug: 'sony-wf-1000xm6',
    brand: 'Sony',
    category: AUDIO,
    shortDescription: 'Premium in-ear earbuds with refined ANC.',
    description:
      'Sony WF-1000XM6 earbuds with dual-chip ANC, Hi-Res audio and a compact charging case.',
    price: 37900,
    compareAtPrice: 40900,
    quantity: 22,
    status: ACTIVE,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    specifications: {
      Type: 'In-ear',
      ANC: 'Yes',
      Battery: '8 + 24 hours',
    },
  },
  {
    title: 'Marshall Major V',
    sku: 'AUD-MRS-MAJ5',
    slug: 'marshall-major-v',
    brand: 'Marshall',
    category: AUDIO,
    shortDescription: 'Retro on-ear headphones with a 100-hour battery.',
    description:
      'Marshall Major V on-ear headphones with signature rock sound and 100 hours of playtime.',
    price: 19900,
    compareAtPrice: 21900,
    quantity: 28,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Type: 'On-ear',
      Battery: '100 hours',
      Bluetooth: '5.3',
    },
  },

  // ---- WATCH ----
  {
    title: 'Apple Watch Series 11',
    sku: 'WTC-APL-WS11-46',
    slug: 'apple-watch-series-11',
    brand: 'Apple',
    category: WATCH,
    shortDescription: 'Flagship Apple smartwatch for health and focus.',
    description:
      'Apple Watch Series 11 with Always-On Retina display, ECG and the newest health sensors.',
    price: 58900,
    compareAtPrice: 62900,
    quantity: 15,
    status: ACTIVE,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    specifications: {
      Case: '46 mm',
      Display: 'Always-On Retina',
      Battery: '18 hours',
      Health: 'ECG',
    },
  },
  {
    title: 'Apple Watch Ultra 3',
    sku: 'WTC-APL-WU3-49',
    slug: 'apple-watch-ultra-3',
    brand: 'Apple',
    category: WATCH,
    shortDescription: 'Rugged titanium watch for extreme endurance.',
    description:
      'Apple Watch Ultra 3 with 49mm titanium case, 3000-nit display and multi-day battery.',
    price: 98900,
    compareAtPrice: 104900,
    quantity: 8,
    status: ACTIVE,
    isFeatured: true,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Case: '49 mm',
      Display: '3000 nits',
      Battery: '36 hours',
      GPS: 'Dual-band',
    },
  },
  {
    title: 'Samsung Galaxy Watch Ultra',
    sku: 'WTC-SAM-GWU-47',
    slug: 'samsung-galaxy-watch-ultra',
    brand: 'Samsung',
    category: WATCH,
    shortDescription: 'Titanium rugged watch for peak performance.',
    description:
      'Samsung Galaxy Watch Ultra with titanium body, sapphire glass and serious sport features.',
    price: 67900,
    compareAtPrice: 71900,
    quantity: 10,
    status: ACTIVE,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    specifications: {
      Case: '47 mm',
      Material: 'Titanium',
      Battery: '2 days',
      GPS: 'Yes',
    },
  },
  {
    title: 'Samsung Galaxy Watch 8',
    sku: 'WTC-SAM-GW8-44',
    slug: 'samsung-galaxy-watch-8',
    brand: 'Samsung',
    category: WATCH,
    shortDescription: 'Polished everyday smartwatch with AMOLED.',
    description:
      'Samsung Galaxy Watch 8 with AMOLED display, sleep coaching and two-day battery.',
    price: 34900,
    compareAtPrice: 37900,
    quantity: 14,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    specifications: {
      Case: '44 mm',
      Display: 'AMOLED',
      Battery: '40 hours',
    },
  },
  {
    title: 'Google Pixel Watch 3',
    sku: 'WTC-GGL-PW3-45',
    slug: 'google-pixel-watch-3',
    brand: 'Google',
    category: WATCH,
    shortDescription: 'Google + Fitbit health tracking on your wrist.',
    description:
      'Google Pixel Watch 3 with Fitbit insights, brighter display and loss-of-pulse detection.',
    price: 42900,
    compareAtPrice: 45900,
    quantity: 12,
    status: ACTIVE,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    specifications: {
      Case: '45 mm',
      Display: 'Actua',
      Battery: '24 hours',
      Health: 'Fitbit',
    },
  },
  {
    title: 'Garmin Fenix 8',
    sku: 'WTC-GRM-FX8-47',
    slug: 'garmin-fenix-8',
    brand: 'Garmin',
    category: WATCH,
    shortDescription: 'Premium multi-sport GPS watch with maps.',
    description:
      'Garmin Fenix 8 with AMOLED display, topo maps and up to 21 days of battery in smartwatch mode.',
    price: 129000,
    compareAtPrice: 139000,
    quantity: 6,
    status: ACTIVE,
    isFeatured: true,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Case: '47 mm',
      Display: 'AMOLED',
      Battery: '21 days',
      Maps: 'TopoActive',
    },
  },
  {
    title: 'Garmin Forerunner 265',
    sku: 'WTC-GRM-FR265-46',
    slug: 'garmin-forerunner-265',
    brand: 'Garmin',
    category: WATCH,
    shortDescription: 'Running-focused watch with AMOLED clarity.',
    description:
      'Garmin Forerunner 265 with training readiness, AMOLED display and accurate GPS.',
    price: 58900,
    compareAtPrice: 62900,
    quantity: 9,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Case: '46 mm',
      Display: 'AMOLED',
      Battery: '13 days',
      Focus: 'Running',
    },
  },
  {
    title: 'Xiaomi Watch S4',
    sku: 'WTC-XIA-WS4-47',
    slug: 'xiaomi-watch-s4',
    brand: 'Xiaomi',
    category: WATCH,
    shortDescription: 'Feature-packed smartwatch at a friendly price.',
    description:
      'Xiaomi Watch S4 with AMOLED display, two-week battery and comprehensive health tracking.',
    price: 17900,
    compareAtPrice: 19900,
    quantity: 25,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    specifications: {
      Case: '47 mm',
      Display: 'AMOLED',
      Battery: '15 days',
    },
  },
  {
    title: 'Huawei Watch GT 5 Pro',
    sku: 'WTC-HUA-GT5P-46',
    slug: 'huawei-watch-gt-5-pro',
    brand: 'Huawei',
    category: WATCH,
    shortDescription: 'Titanium smartwatch with long battery life.',
    description:
      'Huawei Watch GT 5 Pro with titanium build, AMOLED display and up to 14 days of battery.',
    price: 32900,
    compareAtPrice: 35900,
    quantity: 11,
    status: ACTIVE,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    specifications: {
      Case: '46 mm',
      Display: 'AMOLED',
      Battery: '14 days',
    },
  },
  {
    title: 'Amazfit Balance 2',
    sku: 'WTC-AMZ-BAL2-46',
    slug: 'amazfit-balance-2',
    brand: 'Amazfit',
    category: WATCH,
    shortDescription: 'Dual-band GPS watch with fitness insights.',
    description:
      'Amazfit Balance 2 with AMOLED display, dual-band GPS and comprehensive body-composition tracking.',
    price: 24900,
    compareAtPrice: 27900,
    quantity: 16,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Case: '46 mm',
      Display: 'AMOLED',
      Battery: '14 days',
    },
  },

  // ---- ACCESSORY ----
  {
    title: 'Apple MagSafe Charger',
    sku: 'ACC-APL-MGC',
    slug: 'apple-magsafe-charger',
    brand: 'Apple',
    category: ACCESSORY,
    shortDescription: 'Snap-on 15W wireless charger for iPhone.',
    description:
      'Apple MagSafe Charger delivers 15W of fast wireless charging to MagSafe-compatible iPhones.',
    price: 4900,
    compareAtPrice: 5500,
    quantity: 50,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    specifications: {
      Type: 'Wireless',
      Power: '15W',
      Connectivity: 'MagSafe',
    },
  },
  {
    title: 'Anker 65W GaN Charger',
    sku: 'ACC-ANK-G65',
    slug: 'anker-65w-gan-charger',
    brand: 'Anker',
    category: ACCESSORY,
    shortDescription: 'Compact 65W fast charger for laptops and phones.',
    description:
      'Anker 65W GaN wall charger with two USB-C and one USB-A port in a travel-friendly size.',
    price: 3900,
    compareAtPrice: 4500,
    quantity: 60,
    status: ACTIVE,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    specifications: {
      Power: '65W GaN',
      Ports: '2x USB-C, 1x USB-A',
      Size: 'Compact',
    },
  },
  {
    title: 'Logitech MX Master 3S',
    sku: 'ACC-LGT-MX3S',
    slug: 'logitech-mx-master-3s',
    brand: 'Logitech',
    category: ACCESSORY,
    shortDescription: 'Precision wireless mouse for focused work.',
    description:
      'Logitech MX Master 3S with 8K DPI, quiet clicks and 70-day battery on a full charge.',
    price: 15900,
    compareAtPrice: 17900,
    quantity: 20,
    status: ACTIVE,
    isFeatured: true,
    isTrending: false,
    isBestSeller: true,
    specifications: {
      Type: 'Wireless mouse',
      DPI: '8000',
      Battery: '70 days',
    },
  },
  {
    title: 'Logitech MX Keys S',
    sku: 'ACC-LGT-MXKS',
    slug: 'logitech-mx-keys-s',
    brand: 'Logitech',
    category: ACCESSORY,
    shortDescription: 'Backlit wireless keyboard for productivity.',
    description:
      'Logitech MX Keys S with smart backlighting, quiet keys and Multi-Device pairing.',
    price: 18900,
    compareAtPrice: 20900,
    quantity: 18,
    status: ACTIVE,
    isFeatured: true,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Type: 'Keyboard',
      Connectivity: 'Bluetooth + Bolt',
      Backlit: 'Smart',
    },
  },
  {
    title: 'Keychron Q3',
    sku: 'ACC-KYC-Q3',
    slug: 'keychron-q3',
    brand: 'Keychron',
    category: ACCESSORY,
    shortDescription: 'Hot-swappable aluminium mechanical keyboard.',
    description:
      'Keychron Q3 75% mechanical keyboard with CNC aluminium case and hot-swappable switches.',
    price: 27900,
    compareAtPrice: 29900,
    quantity: 10,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Type: 'Mechanical keyboard',
      Layout: '75%',
      Switches: 'Hot-swappable',
    },
  },
  {
    title: 'SteelSeries Arctis Nova 7',
    sku: 'ACC-STS-AN7',
    slug: 'steelseries-arctis-nova-7',
    brand: 'SteelSeries',
    category: ACCESSORY,
    shortDescription: 'Wireless gaming headset with simultaneous audio.',
    description:
      'SteelSeries Arctis Nova 7 with 2.4GHz and Bluetooth, 38-hour battery and comfort fit.',
    price: 28900,
    compareAtPrice: 31900,
    quantity: 12,
    status: ACTIVE,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    specifications: {
      Type: 'Gaming headset',
      Wireless: '2.4GHz + Bluetooth',
      Battery: '38 hours',
    },
  },
  {
    title: 'Samsung T7 Shield 2TB',
    sku: 'ACC-SAM-T7S2',
    slug: 'samsung-t7-shield-2tb',
    brand: 'Samsung',
    category: ACCESSORY,
    shortDescription: 'Rugged portable SSD with 1GB/s speeds.',
    description:
      'Samsung T7 Shield 2TB portable SSD with water and dust resistance and USB 3.2 Gen 2 speeds.',
    price: 21900,
    compareAtPrice: 24900,
    quantity: 15,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    specifications: {
      Type: 'SSD',
      Capacity: '2 TB',
      Interface: 'USB 3.2 Gen 2',
      Protection: 'IP65',
    },
  },
  {
    title: 'Anker 100W Power Bank',
    sku: 'ACC-ANK-PB100',
    slug: 'anker-100w-power-bank',
    brand: 'Anker',
    category: ACCESSORY,
    shortDescription: '24000mAh power bank with 100W output.',
    description:
      'Anker 100W power bank charges laptops, tablets and phones with a 24000mAh capacity.',
    price: 12900,
    compareAtPrice: 14900,
    quantity: 30,
    status: ACTIVE,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    specifications: {
      Capacity: '24000 mAh',
      Power: '100W',
      Ports: '2x USB-C, 1x USB-A',
    },
  },
  {
    title: 'Belkin USB-C Hub 7-in-1',
    sku: 'ACC-BLK-UCH7',
    slug: 'belkin-usb-c-hub-7-in-1',
    brand: 'Belkin',
    category: ACCESSORY,
    shortDescription: 'Expand your USB-C laptop in seven ways.',
    description:
      'Belkin 7-in-1 USB-C hub with HDMI, USB-A, SD card and Gigabit Ethernet ports.',
    price: 9900,
    compareAtPrice: 11900,
    quantity: 25,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Ports: 'HDMI, 3x USB-A, SD, Ethernet',
      Power: 'USB-C PD',
    },
  },
  {
    title: 'Apple Magic Trackpad',
    sku: 'ACC-APL-MT2',
    slug: 'apple-magic-trackpad',
    brand: 'Apple',
    category: ACCESSORY,
    shortDescription: 'Multi-touch trackpad with Force Touch.',
    description:
      'Apple Magic Trackpad with a large glass surface, Force Touch and multi-touch gestures.',
    price: 18900,
    compareAtPrice: 20900,
    quantity: 14,
    status: ACTIVE,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    specifications: {
      Type: 'Trackpad',
      Connectivity: 'Bluetooth',
      Multi_touch: 'Yes',
    },
  },
];

async function main() {
  for (const product of products) {
    await prisma.product.upsert({
      where: { sku: product.sku },
      update: product,
      create: product,
    });
  }
  console.log(`Seeded ${products.length} products`);
}

main()
  .catch((error: unknown) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => prisma.$disconnect());
