ALTER TYPE "OrderStatus" ADD VALUE 'PROCESSING';
ALTER TYPE "OrderStatus" ADD VALUE 'SHIPPED';
ALTER TYPE "OrderStatus" ADD VALUE 'DELIVERED';

ALTER TABLE "orders"
ADD COLUMN "customerPhone" TEXT NOT NULL DEFAULT '',
ADD COLUMN "deliveryAddressLine" TEXT NOT NULL DEFAULT '',
ADD COLUMN "deliveryArea" TEXT NOT NULL DEFAULT '',
ADD COLUMN "deliveryCity" TEXT NOT NULL DEFAULT '',
ADD COLUMN "deliveryPostalCode" TEXT;

ALTER TABLE "orders"
ALTER COLUMN "customerPhone" DROP DEFAULT,
ALTER COLUMN "deliveryAddressLine" DROP DEFAULT,
ALTER COLUMN "deliveryArea" DROP DEFAULT,
ALTER COLUMN "deliveryCity" DROP DEFAULT;
