import type { Product } from './types';

export const demoProducts: Product[] = [
  {
    id: 1,
    slug: 'nova-x1-pro',
    sku: 'MOB-NX1',
    title: 'Nova X1 Pro',
    shortDescription: 'A flagship camera phone, refined for every day.',
    description: 'A beautifully balanced smartphone with a vivid display, all-day battery and a pro-grade camera system.',
    brand: 'Nova',
    category: 'MOBILE',
    price: 89900,
    compareAtPrice: 94900,
    quantity: 12,
    isFeatured: true,
    specifications: { Display: '6.7-inch OLED', Storage: '256 GB', Warranty: '1 year' },
    images: [],
  },
  {
    id: 2,
    slug: 'aero-book-14',
    sku: 'LAP-AB14',
    title: 'AeroBook 14',
    shortDescription: 'Quiet power in an impossibly slim frame.',
    description: 'A light, capable notebook built for focused work and fluid creative sessions.',
    brand: 'Aero',
    category: 'LAPTOP',
    price: 124900,
    compareAtPrice: null,
    quantity: 8,
    isFeatured: true,
    specifications: { Processor: '12-core', Memory: '16 GB', Storage: '512 GB SSD' },
    images: [],
  },
  {
    id: 3,
    slug: 'sonic-air-max',
    sku: 'AUD-SAM',
    title: 'Sonic Air Max',
    shortDescription: 'Immersive sound with calm, all-day comfort.',
    description: 'Wireless over-ear headphones with adaptive noise cancellation and spatial audio.',
    brand: 'Sonic',
    category: 'AUDIO',
    price: 28900,
    compareAtPrice: 32900,
    quantity: 20,
    isFeatured: true,
    specifications: { Battery: '38 hours', Connectivity: 'Bluetooth 5.3', Weight: '254 g' },
    images: [],
  },
  {
    id: 4,
    slug: 'canvas-tab-11',
    sku: 'TAB-CT11',
    title: 'Canvas Tab 11',
    shortDescription: 'Ideas, entertainment and work in one canvas.',
    description: 'A versatile tablet with a crisp display and pen-ready precision.',
    brand: 'Canvas',
    category: 'TABLET',
    price: 54900,
    compareAtPrice: null,
    quantity: 14,
    isFeatured: true,
    specifications: { Display: '11-inch 120Hz', Storage: '128 GB', Battery: '10 hours' },
    images: [],
  },
];
