import type { Product } from './types';

export const demoProducts: Product[] = [
  {
    id: 1,
    slug: 'nova-x1-pro',
    sku: 'MOB-NX1',
    title: 'Nova X1 Pro',
    shortDescription: 'A flagship camera phone, refined for every day.',
    description:
      'A beautifully balanced smartphone with a vivid display, all-day battery and a pro-grade camera system.',
    brand: 'Nova',
    category: 'MOBILE',
    price: 89900,
    compareAtPrice: 94900,
    quantity: 12,
    status: 'ACTIVE',
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    offerStartsAt: null,
    offerEndsAt: null,
    publishedAt: '2026-07-30T00:00:00.000Z',
    specifications: {
      Display: '6.7-inch OLED',
      Storage: '256 GB',
      Warranty: '1 year',
    },
    images: [],
  },
  {
    id: 2,
    slug: 'aero-book-14',
    sku: 'LAP-AB14',
    title: 'AeroBook 14',
    shortDescription: 'Quiet power in an impossibly slim frame.',
    description:
      'A light, capable notebook built for focused work and fluid creative sessions.',
    brand: 'Aero',
    category: 'LAPTOP',
    price: 124900,
    compareAtPrice: null,
    quantity: 8,
    status: 'ACTIVE',
    isFeatured: true,
    isTrending: true,
    isBestSeller: false,
    offerStartsAt: null,
    offerEndsAt: null,
    publishedAt: '2026-07-29T00:00:00.000Z',
    specifications: {
      Processor: '12-core',
      Memory: '16 GB',
      Storage: '512 GB SSD',
    },
    images: [],
  },
  {
    id: 3,
    slug: 'sonic-air-max',
    sku: 'AUD-SAM',
    title: 'Sonic Air Max',
    shortDescription: 'Immersive sound with calm, all-day comfort.',
    description:
      'Wireless over-ear headphones with adaptive noise cancellation and spatial audio.',
    brand: 'Sonic',
    category: 'AUDIO',
    price: 28900,
    compareAtPrice: 32900,
    quantity: 20,
    status: 'ACTIVE',
    isFeatured: true,
    isTrending: false,
    isBestSeller: true,
    offerStartsAt: null,
    offerEndsAt: null,
    publishedAt: '2026-07-28T00:00:00.000Z',
    specifications: {
      Battery: '38 hours',
      Connectivity: 'Bluetooth 5.3',
      Weight: '254 g',
    },
    images: [],
  },
  {
    id: 4,
    slug: 'canvas-tab-11',
    sku: 'TAB-CT11',
    title: 'Canvas Tab 11',
    shortDescription: 'Ideas, entertainment and work in one canvas.',
    description:
      'A versatile tablet with a crisp display and pen-ready precision.',
    brand: 'Canvas',
    category: 'TABLET',
    price: 54900,
    compareAtPrice: null,
    quantity: 14,
    status: 'ACTIVE',
    isFeatured: true,
    isTrending: false,
    isBestSeller: false,
    offerStartsAt: null,
    offerEndsAt: null,
    publishedAt: '2026-07-27T00:00:00.000Z',
    specifications: {
      Display: '11-inch 120Hz',
      Storage: '128 GB',
      Battery: '10 hours',
    },
    images: [],
  },
  {
    id: 5,
    slug: 'pulse-watch-2',
    sku: 'WTC-PW2',
    title: 'Pulse Watch 2',
    shortDescription: 'Health insights that keep pace with your day.',
    description:
      'A bright AMOLED smartwatch with heart, sleep and SpO2 tracking built for everyday wear.',
    brand: 'Pulse',
    category: 'WATCH',
    price: 27900,
    compareAtPrice: 31900,
    quantity: 16,
    status: 'ACTIVE',
    isFeatured: true,
    isTrending: true,
    isBestSeller: false,
    offerStartsAt: null,
    offerEndsAt: null,
    publishedAt: '2026-07-26T00:00:00.000Z',
    specifications: {
      Display: '1.4-inch AMOLED',
      Battery: '10 days',
      Health: 'ECG & SpO2',
    },
    images: [],
  },
  {
    id: 6,
    slug: 'voltcharge-65w',
    sku: 'ACC-VC65',
    title: 'VoltCharge 65W',
    shortDescription: 'A pocket-sized GaN charger for every device.',
    description:
      'A compact 65W GaN charger that powers laptops and phones from two USB-C ports.',
    brand: 'Volt',
    category: 'ACCESSORY',
    price: 3900,
    compareAtPrice: 4500,
    quantity: 60,
    status: 'ACTIVE',
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    offerStartsAt: null,
    offerEndsAt: null,
    publishedAt: '2026-07-25T00:00:00.000Z',
    specifications: {
      Power: '65W GaN',
      Ports: '2x USB-C',
      Size: 'Compact',
    },
    images: [],
  },
  {
    id: 7,
    slug: 'nova-x1-lite',
    sku: 'MOB-NX1L',
    title: 'Nova X1 Lite',
    shortDescription: 'The Nova experience, trimmed to essentials.',
    description:
      'A focused phone with a vivid OLED display, dependable battery and clean software.',
    brand: 'Nova',
    category: 'MOBILE',
    price: 54900,
    compareAtPrice: null,
    quantity: 24,
    status: 'ACTIVE',
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    offerStartsAt: null,
    offerEndsAt: null,
    publishedAt: '2026-07-24T00:00:00.000Z',
    specifications: {
      Display: '6.5-inch OLED',
      Storage: '128 GB',
      Battery: '5000 mAh',
    },
    images: [],
  },
  {
    id: 8,
    slug: 'aero-book-16',
    sku: 'LAP-AB16',
    title: 'AeroBook 16',
    shortDescription: 'Desktop-level power in a portable shell.',
    description:
      'A performance notebook with a 14-core processor and a roomy display for demanding work.',
    brand: 'Aero',
    category: 'LAPTOP',
    price: 154900,
    compareAtPrice: 164900,
    quantity: 9,
    status: 'ACTIVE',
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    offerStartsAt: null,
    offerEndsAt: null,
    publishedAt: '2026-07-23T00:00:00.000Z',
    specifications: {
      Processor: '14-core',
      Memory: '32 GB',
      Storage: '1 TB SSD',
    },
    images: [],
  },
  {
    id: 9,
    slug: 'sonic-pods',
    sku: 'AUD-SP',
    title: 'Sonic Pods',
    shortDescription: 'Tiny buds, big noise-cancelling presence.',
    description:
      'Compact true-wireless earbuds with active noise cancellation and sweat resistance.',
    brand: 'Sonic',
    category: 'AUDIO',
    price: 12900,
    compareAtPrice: 14900,
    quantity: 32,
    status: 'ACTIVE',
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    offerStartsAt: null,
    offerEndsAt: null,
    publishedAt: '2026-07-22T00:00:00.000Z',
    specifications: {
      Battery: '6 hours',
      ANC: 'Yes',
      WaterResistance: 'IPX4',
    },
    images: [],
  },
  {
    id: 10,
    slug: 'canvas-tab-8',
    sku: 'TAB-CT8',
    title: 'Canvas Tab 8',
    shortDescription: 'A pocket-friendly tablet for light browsing.',
    description:
      'An 8-inch tablet that slips into a bag for reading, video and casual apps.',
    brand: 'Canvas',
    category: 'TABLET',
    price: 32900,
    compareAtPrice: null,
    quantity: 20,
    status: 'ACTIVE',
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    offerStartsAt: null,
    offerEndsAt: null,
    publishedAt: '2026-07-21T00:00:00.000Z',
    specifications: {
      Display: '8.4-inch',
      Storage: '64 GB',
      Battery: '8 hours',
    },
    images: [],
  },
  {
    id: 11,
    slug: 'pulse-band',
    sku: 'WTC-PB',
    title: 'Pulse Band',
    shortDescription: 'A featherlight band for sleep and step tracking.',
    description:
      'A slim fitness band with a two-week battery and reliable sleep and activity tracking.',
    brand: 'Pulse',
    category: 'WATCH',
    price: 12900,
    compareAtPrice: 14900,
    quantity: 28,
    status: 'ACTIVE',
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    offerStartsAt: null,
    offerEndsAt: null,
    publishedAt: '2026-07-20T00:00:00.000Z',
    specifications: {
      Display: '1.1-inch',
      Battery: '14 days',
      Trackers: 'Sleep & steps',
    },
    images: [],
  },
  {
    id: 12,
    slug: 'aero-sleeve-13',
    sku: 'ACC-AS13',
    title: 'Aero Sleeve 13',
    shortDescription: 'Protective felt sleeve for 13-inch laptops.',
    description:
      'A wool-felt laptop sleeve with a plush interior that guards a 13-inch device on the move.',
    brand: 'Aero',
    category: 'ACCESSORY',
    price: 3900,
    compareAtPrice: null,
    quantity: 40,
    status: 'ACTIVE',
    isFeatured: true,
    isTrending: false,
    isBestSeller: false,
    offerStartsAt: null,
    offerEndsAt: null,
    publishedAt: '2026-07-19T00:00:00.000Z',
    specifications: {
      Material: 'Wool felt',
      Fits: '13-inch',
      Padding: '1 cm',
    },
    images: [],
  },
];
